# Generated by Django 3.0.7 on 2020-07-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='name',
        ),
        migrations.AddField(
            model_name='config',
            name='plan',
            field=models.CharField(default='free', max_length=200, unique=True, verbose_name='Plan'),
            preserve_default=False,
        ),
    ]
