# Generated by Django 3.0.7 on 2020-07-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler', '0002_auto_20200708_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='keywords',
            field=models.CharField(max_length=10000, verbose_name='Keyword'),
        ),
    ]
