# Generated by Django 3.0.7 on 2020-07-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler', '0004_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='list',
            field=models.CharField(max_length=200, verbose_name='List'),
        ),
    ]
