# Generated by Django 3.0.7 on 2020-07-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler', '0007_delete_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News'},
        ),
        migrations.AddField(
            model_name='news',
            name='order_id',
            field=models.CharField(default='', max_length=200, verbose_name='Order_id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(default='', max_length=200, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
