# Generated by Django 3.0.7 on 2020-07-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler', '0008_auto_20200719_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='status',
            field=models.CharField(default='Not Started', max_length=200, verbose_name='Status'),
        ),
    ]
