# Generated by Django 3.0.7 on 2020-07-19 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler', '0009_manifest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='news',
            name='status',
        ),
    ]
