# Generated by Django 3.0.7 on 2020-07-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler', '0010_auto_20200719_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='date',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='news',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title',
        ),
        migrations.AddField(
            model_name='news',
            name='message',
            field=models.CharField(default='', max_length=1000, verbose_name='Message'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='platform',
            field=models.CharField(default='', max_length=200, verbose_name='Platform'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='sender_name',
            field=models.CharField(default='', max_length=200, verbose_name='Sender Name'),
            preserve_default=False,
        ),
    ]
