# Generated by Django 3.0.7 on 2020-08-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler', '0012_news_news_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='message',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='platform',
            new_name='Platform',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='sender_name',
            new_name='Sender_Name',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='time',
            new_name='Time',
        ),
        migrations.RemoveField(
            model_name='news',
            name='link',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_time',
        ),
        migrations.AddField(
            model_name='news',
            name='Message_Link',
            field=models.CharField(default='', max_length=200, verbose_name='Message Link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='Message_Time',
            field=models.CharField(default='', max_length=200, verbose_name='Message Time'),
            preserve_default=False,
        ),
    ]
