# Generated by Django 3.0.7 on 2020-08-05 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler', '0014_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='duration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Crawler.Duration', verbose_name='ِDuration'),
        ),
    ]
